version: 2

machine:
  services:
    - docker
  timezone: Europe/Paris

jobs:

  build:
    working_directory: /go/src/cachet
    docker:
      - image: circleci/golang:1.10
        environment:
          GOPATH: /go
    steps:
      - checkout:
          path: /go/src/cachet
      - run:
          name: Saving latest tag...
          command: git tag | sort | tail -1 > /go/src/cachet/cachet-monitor.tag
      - run:
          name: Checking GO version...
          command: go version
      - run:
          name: Downloading dependencies...
          command: go get .
      - run:
          name: Building...
          command: go build -ldflags "-X main.AppBranch=`cat /go/src/cachet/cachet-monitor.tag` -X main.Build=${CIRCLE_SHA1} -X main.BuildDate=`date +%Y-%m-%d_%H:%M:%S`" -o cachet_monitor
      - run:
          name: Changed permissions...
          command: chmod +x cachet_monitor
      - run:
          name: Checking delivery...
          command: ls -l cachet_monitor
      - save_cache:
          key: cachet-monitor-delivery-cache-{{ checksum "cachet_monitor" }}
          paths:
            - /go/src/cachet

  test:
    working_directory: /go/src/cachet
    docker:
      - image: circleci/golang:1.10
    steps:
      - restore-cache:
          keys:
            - cachet-monitor-delivery-cache-
      - run:
          name: Changed permissions...
          command: chmod +x ./cachet_monitor
      - run:
          name: Listing build version...
          command: ./cachet_monitor --version
      - run:
          name: Testing YML configuration...
          command: ./cachet_monitor -c example.config.yml --config-test
      - run:
          name: Testing JSON configuration...
          command: ./cachet_monitor -c example.config.json --config-test
      - store_artifacts:
          path: /go/src/cachet/cachet_monitor
          destination: artifact-file

  release:
    working_directory: /go/src/cachet
    docker:
      - image: circleci/golang:1.10
    steps:
      - restore-cache:
          keys:
            - cachet-monitor-delivery-cache-
      - run:
          name: Downloading GitHub Release...
          command: wget -O./ghr.zip https://github.com/tcnksm/ghr/releases/download/v0.5.4/ghr_v0.5.4_linux_amd64.zip && unzip ghr.zip && chmod +x ./ghr
      - run:
          name: Preparing release...
          command: mkdir ./dist && mv ./cachet_monitor ./dist && cat cachet-monitor.tag
      - run:
          name: GitHub Release...
          command: |
            LATEST_TAG=`cat cachet-monitor.tag`
            echo "Latest tag: ${LATEST_TAG}"
            if [[ "`echo ${LATEST_TAG} | tr '[:upper:]' '[:lower:]'`" == *"snapshot"* ]]; then
              echo "Prereleasing '${LATEST_TAG}'" && ./ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} --delete --prerelease --replace ${LATEST_TAG} ./dist
              echo "Prereleasing '${LATEST_TAG}'" && ./ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} --delete --prerelease --replace snapshot ./dist
            else
              echo "Releasing '${LATEST_TAG}'" && ./ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} --delete --replace ${LATEST_TAG} ./dist
            fi

  docker_build:
    working_directory: /go/src/cachet
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout:
          path: /go/src/cachet
      - run:
          name: Saving latest tag...
          command: |
            mkdir /tmp/workspace && \
            git tag | sort | tail -1 > /tmp/workspace/cachet-monitor.tag
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            LATEST_TAG=`cat /tmp/workspace/cachet-monitor.tag`
            docker build --force-rm -t ${DOCKERHUB_UID}/cachet-monitor:${LATEST_TAG} -t ${DOCKERHUB_UID}/cachet-monitor:latest .
      - run:
          name: DockerHub Release...
          command: |
            LATEST_TAG=`cat /tmp/workspace/cachet-monitor.tag`
            docker login -e ${DOCKERHUB_EMAIL} -u ${DOCKERHUB_UID} -p ${DOCKERHUB_PWD}
            docker push ${DOCKERHUB_UID}/cachet-monitor:${LATEST_TAG}
            docker push ${DOCKERHUB_UID}/cachet-monitor:latest

workflows:
  version: 2
  build_binary:
    jobs:
      - build
      - test:
          requires:
            - build
      - release:
          requires:
            - build
            - test

  build_docker:
    jobs:
      - docker_build:
          context: dockerhub
